#!/usr/bin/env bash
# scripts/lib/caddy.sh — Caddy site helpers.
set -euo pipefail

# shellcheck source=common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

CADDY_TEMPLATE="${VPSMGR_ROOT}/templates/Caddyfile.site.j2"

caddy_ensure_sites_dir() {
    require_command caddy
    mkdir -p "${CADDY_SITES_DIR}"
    chmod 0755 "${CADDY_SITES_DIR}"
}

caddy_global_configured() {
    [[ -f ${CADDY_GLOBAL_CONFIG} ]] && grep -qF "import ${CADDY_SITES_DIR}/*" "${CADDY_GLOBAL_CONFIG}" 2>/dev/null
}

caddy_ensure_global_config() {
    local cfg="${CADDY_GLOBAL_CONFIG}"
    mkdir -p "$(dirname "${cfg}")"
    if [[ ! -f ${cfg} ]] || ! caddy_global_configured; then
        : > "${cfg}"
        {
            echo "# Global Caddyfile generated by vpsmgr"
            echo "import ${CADDY_SITES_DIR}/*"
        } >> "${cfg}"
        chmod 0644 "${cfg}"
        vpsmgr_log INFO "Caddy global config ensured"
    fi
}

caddy_site_path() {
    local domain="$1"
    echo "${CADDY_SITES_DIR}/${domain}.caddy"
}

caddy_render_site() {
    local domain="$1"
    local type="$2"
    local webroot="$3"
    local php_socket="${4:-}"
    local proxy_target="${5:-}"

    local out block
    out=$(caddy_site_path "${domain}")

    export DOMAIN="${domain}"
    export WEBROOT="${webroot}"
    export PHP_BLOCK=""
    export PROXY_BLOCK=""
    export TRY_FILES=""

    case "${type}" in
        static)
            export TRY_FILES="    try_files {path} {path}/ /index.html"
            ;;
        php)
            if [[ -z ${php_socket} ]]; then
                die_internal "php_socket required for php site"
            fi
            export PHP_BLOCK="    php_fastcgi unix/${php_socket}"
            ;;
        wordpress)
            if [[ -z ${php_socket} ]]; then
                die_internal "php_socket required for wordpress site"
            fi
            export TRY_FILES="    try_files {path} {path}/ /index.php?{query}"
            export PHP_BLOCK="    php_fastcgi unix/${php_socket}"
            ;;
        reverse_proxy)
            if [[ -z ${proxy_target} ]]; then
                die_internal "proxy_target required for reverse_proxy site"
            fi
            export PROXY_BLOCK="    reverse_proxy ${proxy_target}"
            ;;
        *)
            die_internal "unknown site type: ${type}"
            ;;
    esac

    render_template "${CADDY_TEMPLATE}" "${out}"
    chmod 0644 "${out}"
    vpsmgr_log INFO "rendered Caddy config for ${domain}"
}

caddy_remove_site() {
    local domain="$1"
    local out
    out=$(caddy_site_path "${domain}")
    if [[ -f ${out} ]]; then
        rm -f "${out}"
        vpsmgr_log INFO "removed Caddy config for ${domain}"
    fi
}

caddy_validate() {
    require_command caddy
    caddy validate --config "${CADDY_GLOBAL_CONFIG}" 2>&1
}

caddy_reload() {
    require_command systemctl
    caddy_validate >/dev/null || die_dependency "caddy config validation failed"
    systemctl reload caddy || die_internal "failed to reload caddy"
    vpsmgr_log INFO "caddy reloaded"
}
