#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/lib"

# shellcheck source=scripts/lib/common.sh
source "$LIB_DIR/common.sh"
# shellcheck source=scripts/lib/caddy.sh
source "$LIB_DIR/caddy.sh"
# shellcheck source=scripts/lib/php.sh
source "$LIB_DIR/php.sh"
# shellcheck source=scripts/lib/db.sh
source "$LIB_DIR/db.sh"

ensure_root

# --- Parse args ---
PHP_VERSION=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --php-version) PHP_VERSION="$2"; shift 2 ;;
        --api-token)   API_TOKEN="$2"; shift 2 ;;
        --db-root-pass) DB_ROOT_PASSWORD="$2"; shift 2 ;;
        *) echo "Usage: $0 [--php-version <ver>] [--api-token <tok>] [--db-root-pass <pass>]" >&2; exit 1 ;;
    esac
done

echo "=== VPS Manager Bootstrap ==="

# --- 1. Create runtime directories ---
for d in "$STATE_DIR" "$LOG_DIR" "$BACKUP_DIR" "$CADDY_SITES_DIR"; do
    mkdir -p "$d"
done

# --- 2. Install packages ---
apt-get update -qq
apt-get install -y -qq curl wget openssl git unzip tar gzip mysql-client 2>/dev/null || true

# --- 3. Install MariaDB ---
db_install_mariadb

if [[ -n "${DB_ROOT_PASSWORD:-}" ]]; then
    mysql -u root <<SQL
ALTER USER 'root'@'localhost' IDENTIFIED BY '${DB_ROOT_PASSWORD}';
FLUSH PRIVILEGES;
SQL
    info "MariaDB root password set"
fi

# --- 4. Install Caddy ---
caddy_install

# --- 5. Install PHP ---
if [[ -z "$PHP_VERSION" ]]; then
    PHP_VERSION="$(php_resolve_version)"
fi
PHP_VERSION="$(php_install "$PHP_VERSION")"

# --- 6. Install WP-CLI ---
# shellcheck source=scripts/lib/wp.sh
source "$LIB_DIR/wp.sh"
wp_install_cli

# --- 7. Write config ---
mkdir -p /etc/vpsmgr/templates
cat > /etc/vpsmgr/vpsmgr.conf <<CONF
# VPS Manager — Generated by bootstrap.sh
state_dir=$STATE_DIR
log_dir=$LOG_DIR
backup_dir=$BACKUP_DIR
webroot_base=$WEBROOT_BASE
caddy_sites_dir=$CADDY_SITES_DIR
api_host=127.0.0.1
api_port=8000
api_token=${API_TOKEN:-}
php_default_version=$PHP_VERSION
db_root_user=root
db_root_password=${DB_ROOT_PASSWORD:-}
backup_retention_days=30
CONF

# --- 8. Deploy templates ---
cp "$SCRIPT_DIR/../templates/Caddyfile.site.j2" /etc/vpsmgr/templates/
cp "$SCRIPT_DIR/../templates/php-pool.conf.j2" /etc/vpsmgr/templates/
cp "$SCRIPT_DIR/../templates/wp-config.tmpl" /etc/vpsmgr/templates/
chmod 644 /etc/vpsmgr/templates/*

# --- 9. Disable SSH password auth for non-sftp users ---
sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config 2>/dev/null || true
sed -i 's/^PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config 2>/dev/null || true
systemctl reload sshd 2>/dev/null || systemctl reload ssh 2>/dev/null || true

# --- 10. Setup log rotation ---
cat > /etc/logrotate.d/vpsmgr <<'LOGROTATE'
/var/log/vpsmgr/*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
LOGROTATE

echo ""
echo "=== Bootstrap complete ==="
echo "PHP version: $PHP_VERSION"
echo "Config: /etc/vpsmgr/vpsmgr.conf"
echo "Logs: /var/log/vpsmgr/"
echo "State: /var/lib/vpsmgr/sites/"
echo "Backups: /var/backups/vpsmgr/"
echo "Caddy sites: /etc/caddy/sites/"
echo ""
